services:
  echo:
    container_name: echo
    image: ghcr.io/traipoap/echo:latest
    build: 
      context: .
    expose:
      - 8080
    networks:
      - proxy
      
networks:
  proxy:
    external: true